# Generated by Django 4.2.16 on 2026-09-21 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Destination name (unique).', max_length=200, unique=True)),
                ('country', models.CharField(help_text='Country the destination is in.', max_length=100)),
                ('description', models.TextField(help_text='Full description of the destination.')),
                ('category', models.CharField(choices=[('beach', 'Beach'), ('mountain', 'Mountain'), ('city', 'City'), ('cultural', 'Cultural'), ('adventure', 'Adventure'), ('relaxation', 'Relaxation')], help_text='Primary category of the destination.', max_length=20)),
                ('climate', models.CharField(choices=[('tropical', 'Tropical'), ('dry', 'Dry'), ('temperate', 'Temperate'), ('continental', 'Continental'), ('polar', 'Polar')], help_text='Predominant climate.', max_length=20)),
                ('best_time_to_visit', models.CharField(help_text='Recommended season/months to visit.', max_length=200)),
                ('avg_daily_cost', models.DecimalField(decimal_places=2, help_text='Average cost per day in USD.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'category'], name='destination_country_c7c612_idx'), models.Index(fields=['climate'], name='destination_climate_5ffe0c_idx')],
            },
        ),
    ]
