# Generated by Django 4.2.16 on 2026-09-21 12:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', help_text='Access level of the collaborator.', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Trip title.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional trip description.')),
                ('start_date', models.DateField(help_text='Trip start date.')),
                ('end_date', models.DateField(help_text='Trip end date.')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Planned total budget in USD.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_spent', models.DecimalField(decimal_places=2, default=0, help_text='Amount actually spent so far.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('booked', 'Booked'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', help_text='Current trip status.', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Whether the itinerary is publicly visible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborators', models.ManyToManyField(blank=True, help_text='Users this itinerary is shared with.', related_name='shared_itineraries', through='itineraries.Collaboration', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(help_text='Primary destination for this trip.', on_delete=django.db.models.deletion.PROTECT, related_name='itineraries', to='destinations.destination')),
                ('owner', models.ForeignKey(help_text='User who owns/created this itinerary.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_itineraries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Itineraries',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField(help_text='1-based day index within the trip.')),
                ('date', models.DateField(help_text='Calendar date for this day.')),
                ('title', models.CharField(help_text='Short title for the day.', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Free-form notes for the day.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, help_text='Activities planned for this day.', related_name='daily_plans', to='bookings.activity')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='itineraries.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.AddField(
            model_name='collaboration',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='itineraries.itinerary'),
        ),
        migrations.AddField(
            model_name='collaboration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['owner', 'status'], name='itineraries_owner_i_768523_idx'),
        ),
        migrations.AddIndex(
            model_name='itinerary',
            index=models.Index(fields=['start_date', 'end_date'], name='itineraries_start_d_ad6b7c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('itinerary', 'day_number')},
        ),
        migrations.AlterUniqueTogether(
            name='collaboration',
            unique_together={('itinerary', 'user')},
        ),
    ]
