# Generated by Django 4.2.16 on 2026-09-30 20:54

from django.db import migrations, models
import travel_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional profile picture.', null=True, upload_to='profiles/', validators=[travel_api.validators.validate_image_size, travel_api.validators.validate_image_type]),
        ),
    ]
