# Generated by Django 4.2.16 on 2026-09-30 20:54

from django.db import migrations, models
import travel_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', validators=[travel_api.validators.validate_image_size, travel_api.validators.validate_image_type]),
        ),
    ]
