# Generated by Django 4.2.16 on 2026-09-30 20:54

from django.db import migrations, models
import travel_api.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='accommodations/', validators=[travel_api.validators.validate_image_size, travel_api.validators.validate_image_type]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/', validators=[travel_api.validators.validate_image_size, travel_api.validators.validate_image_type]),
        ),
    ]
